In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
#some example of the sentences
senten=['I am a boy','I am a good Programmer','The glass of water','juice is cold','one cup of tea','food was testy',
       'Are you able to understand all of these vey well']


In [8]:
senten

['I am a boy',
 'I am a good Programmer',
 'The glass of water',
 'juice is cold',
 'one cup of tea',
 'food was testy',
 'Are you able to understand all of these vey well']

In [9]:
#these is for vocabulary size
voca_size=9500


# One Hot Representation

In [10]:
onehot=[one_hot(word,voca_size)for word in senten]
onehot

[[4929, 4658, 7839, 8362],
 [4929, 4658, 7839, 2177, 2212],
 [2135, 1505, 5659, 1224],
 [9180, 8578, 4392],
 [4190, 3598, 5659, 1082],
 [4049, 9157, 1624],
 [1772, 734, 6268, 1670, 538, 1106, 5659, 3795, 6387, 327]]

basically above function returns the index number  of all words from vocabulary  

# word Embedding Representation

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [14]:
length=10

In [18]:
embedded=pad_sequences(onehot,padding='pre',maxlen=length)

the above code will add padding to sentence because embeddaing will work very good when length is equall of all sentences 
this will hepl to create good embedding matrix
it will make all sentence length equal to 10 

In [19]:
print(embedded)

[[   0    0    0    0    0    0 4929 4658 7839 8362]
 [   0    0    0    0    0 4929 4658 7839 2177 2212]
 [   0    0    0    0    0    0 2135 1505 5659 1224]
 [   0    0    0    0    0    0    0 9180 8578 4392]
 [   0    0    0    0    0    0 4190 3598 5659 1082]
 [   0    0    0    0    0    0    0 4049 9157 1624]
 [1772  734 6268 1670  538 1106 5659 3795 6387  327]]


In [20]:
dime=10 #this will make 10 dimension feature representation

In [21]:
model=Sequential()
model.add(Embedding(voca_size,dime,input_length=length))
model.compile('adam','mse')
#adam optimizer and mean square error


In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 10)            95000     
Total params: 95,000
Trainable params: 95,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
print(model.predict(embedded))

[[[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]
  [-0.0042007  -0.02967262  0.04715288  0.04883567 -0.03446328
    0.03531807  0.01888419  0.02159152 -0.02264267 -0.03804442]
  [-0.02115151  0.04364954  0.01512125 -0.01852613  0.03467137
    0.0111343  -0.0363335   0.00666533 -0.044536

In [24]:
embedded[0]

array([   0,    0,    0,    0,    0,    0, 4929, 4658, 7839, 8362])

In [25]:
print(model.predict(embedded[0]))

[[[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.01400484  0.04411885 -0.01842447  0.04538265 -0.01973795
    0.03313405  0.01728343  0.03607938 -0.00110734  0.00479014]]

 [[-0.0042007  -0.02967262  0.04715288  0.04883567 -0.03446328
    0.03531807  0.01888419  0.02159152 -0.02264267 -0.03804442]]

 [[-0.02115151  0.04364954  0.01512125 -0.01852613  0.03467137
    0.0111343  -0.0363335   0.0066

In [3]:
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

# define documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents this is will be done with hashmap every word will get certain index number to avoid colloision it
#  is preferable to keep vocab_size more
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[40, 46], [47, 45], [22, 16], [20, 45], [18], [23], [30, 16], [14, 47], [30, 45], [41, 49, 46, 34]]


In [4]:
# pad documents to a max length of 4 words we will do padding
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[40 46  0  0]
 [47 45  0  0]
 [22 16  0  0]
 [20 45  0  0]
 [18  0  0  0]
 [23  0  0  0]
 [30 16  0  0]
 [14 47  0  0]
 [30 45  0  0]
 [41 49 46 34]]


In [5]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [7]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998
